-- https://programmers.co.kr/learn/courses/30/parts/17042
-- SELECT

-- 모든 레코드 조회하기 (LEVEL 1)
-- SELECT 사용
SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID;

-- 역순 정렬하기 (LEVEL 1)
-- ORDER BY (ASC, DESC) 사용
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;

-- 아픈 동물 찾기 (LEVEL 1)
-- WHERE COLUMN == CONDITION 사용
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION='Sick' ORDER BY ANIMAL_ID;

-- 어린 동물 찾기 (LEVEL 1)
-- WHERE COLUMN <> CONDITION 사용 (<>: Not Equal)
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION <> 'Aged' ORDER BY ANIMAL_ID;

-- 동물의 아이디와 이름 (LEVEL 1)
-- SELECT MULTIPLE COLUMN 사용
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID;

-- 여러 기준으로 정렬하기 (LEVEL 1)
-- ORDER BY COLUMN1, COLUMN2... 사용
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME, DATETIME DESC;

-- 상위 n개 레코드 (LEVEL 1)
-- LIMIT 사용
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;